### ISSUE TITLE
Roadmap to stable v2

### ISSUE THREAD

**Issue by philippkuehn** [ueberdosis/tiptap#2087]
Hey, it’s amazing how far tiptap v2 beta has already made it. Thanks a lot for your support. 🙌

I'm trying to make a list here of features we still want to implement until stable v2.
This list is not final. If you have any wishes, please comment below.

### Features
- [x] Autolink on type #1209
- [x] Find a better implementation of `getCharacterCount`, #1839

### Breaking Changes
- [x] Add custom implementation of `InputRule`, #1997
- [x] Replace `defaultOptions` with `addOptions()` for extensions, #2088 
- [ ] Refactor core commands (possibly simplify, merge, find clearer names, etc.)
- [x] Use the [new storage feature](https://github.com/ueberdosis/tiptap/pull/2069) in `CharacterCount`
- [x] Use the [new storage feature](https://github.com/ueberdosis/tiptap/pull/2069) in `CollaborationCursor`

### QA
- [x] Add at least one test for every example

### Docs
- [x] Add docs for missing [commands](https://tiptap.dev/api/commands)

### Misc
- [x] Switch setup from yarn to npm

**Comment by yellow1912** [comment]
I think you need to document these BreakingChanges and what to do as well. I had to track down the issues to understand what went wrong and the changes needed.

**Comment by emma-campbell** [comment]
Hey, any plans on implementing #763? I am looking at a use case where I would need to force a title, subtitle & text (paragraph) "blocks". Would be a great feature to have!

**Comment by tylerforesthauser** [comment]
Perhaps this would work for you?

https://tiptap.dev/examples/custom-document

**Comment by cadars** [comment]
> Do you know where these options may be documented? 

Have a look at the Schema docs, this part in particular: https://tiptap.dev/api/schema#the-node-schema

**Comment by philippkuehn** [comment]
> > Perhaps this would work for you?
> > https://tiptap.dev/examples/custom-document
> 
> I tried this example, and was able to get the title but have struck out with subtitle as I had trouble finding documentation on what a valid string for the content option would be, besides `block+` or `heading block*`, to support a subtitle. Do you know where these options may be documented? I saw the issue I previously mentioned had been closed with a possibility of being implemented for v2, but couldn't seem to find anything about whether or not it would be implemented.

you can create a `title` and `subtitle` node. after that overwrite the document content expression with `title subtitle block+`.

**Comment by emma-campbell** [comment]
> you can create a `title` and `subtitle` node. after that overwrite the document content expression with `title subtitle block+`.

Yep, this did the trick. I figured I wasn't connecting something somewhere. Much thanks ☺️

**Comment by rezaffm** [comment]
Hi, would you mind sharing your solution (snippets)? Would be great.

**Comment by emma-campbell** [comment]
> Hi, would you mind sharing your solution (snippets)? Would be great.

Not sure if you were talking to me, but sure! Here's a minimal reproduction...

Using Vue, inside the template tag...

```html
<div class="editor-wrapper">
  <div class="alerts">
    <a-alert
      v-if="this.changed == true && this.saved == false"
      type="warning"
      :message="$t('heading.warning')"
      :description="$t('warnings.unsaved')"
      show-icon
    />
  </div>
  <div class="editor">
    <!-- Menu Bar -->
    <a-row type="flex" class="menu-bar">
      <!-- NOTE: controls is a computed field, which just returns a list of all the menu items -->
      <div v-for="c in controls" :key="$t(c.title)">
        <toggleButton :title="$t(c.title)" :onClick="c.onClick" :icon="c.icon" />
        <a-divider v-if="sections.includes(c.title)" type="vertical" />
      </div>
    </a-row>
    <!-- Editor Content -->
    <editor-content :editor="editor" />
  </div>
  <div class="actions">
    <a-button type="primary" @click="onSave()">
      {{ $t('button.save') }}
    </a-button>
  </div>
</div>
```

then, inside the script tag...

```typescript
import { Editor, EditorContent } from '@tiptap/vue-2';
import { Node } from '@tiptap/core';
import Document from '@tiptap/extension-document';
import Placeholder from '@tiptap/extension-placeholder';

const Title = Node.create({
  name: 'title',
  content: 'inline*',
  parseHTML() {
    return [{ tag: 'h1' }];
  },
  renderHTML({ HTMLAttributes }) {
    return ['h1', HTMLAttributes, 0];
  }
});

const Subtitle = Node.create({
  name: 'subtitle',
  content: 'inline*',
  parseHTML() {
    return [{ tag: 'h2' }];
  },
  renderHTML({ HTMLAttributes }) {
    return ['h2', HTMLAttributes, 0];
  }
});

const CustomDocument = Document.extend({
  content: 'title subtitle block+'
});

export default {
  data() {
      return {
          editor: null,
      }
  },
  mounted() {
    this.editor = new Editor({
      content: this.text,   // computed field that wraps text fields in html
      extensions: [
        CustomDocument,
        Title,
        Subtitle,
        Placeholder.configure({
          placeholder: ({node}) => {
            if (node.type.name === 'title') {
              return 'Title...';
            } else if (node.type.name === 'subtitle') {
              return 'Subtitle...';
            }
            return 'Write your content here...';
          }
       })
    ]});
  }
}
```

and then finally, the styling...

```less
<style lang="less">
.ProseMirror {
  padding-top: 20px;
  padding-left: 14px;
  padding-right: 14px;
  padding-bottom: 0px;
  color: rgba(0, 0, 0, 0.65);
  font-size: 14px;
  line-height: 27px;
  background-color: #fff;
  background-image: none;
  border-top: 1px solid #d9d9d9;
  max-width: 100%;
  transition: all 0.3s;

  h1 {
    font-size: 46px;
    margin-bottom: 36px;
  }

  h1::before {
    content: attr(data-placeholder);
    float: left;
    color: #adb5bd;
    pointer-events: none;
    height: 0;
  }

  h2 {
    font-size: 32px;
  }

  h2::before {
    content: attr(data-placeholder);
    float: left;
    color: #adb5bd;
    pointer-events: none;
    height: 0;
  }

  p {
    font-size: 14px;
  }

  p::before {
    content: attr(data-placeholder);
    float: left;
    color: #adb5bd;
    pointer-events: none;
    height: 0;
  }

  &:hover {
    border-color: #238dde;
    border-right-width: 1px !important;
  }
}

.ProseMirror-focused {
  border-color: #238dde;
  border-right-width: 1px !important;
  outline: 0;
  box-shadow: 0 0 0 2px rgb(0 112 210 / 20%);
}
</style>

<style lang="less" scoped>
.editor-wrapper {
  .editor {
    max-width: 54.5em;
    border: 1px solid #d9d9d9;
    border-radius: 4px;

    .menu-item {
      border: 0;
      box-shadow: none;
    }
  }

  .actions {
    display: flex;
    flex-flow: row wrap;
    justify-content: flex-end;
    margin-top: 1em;
  }
}
</style>
```
This (in combination with ant-design and some styling) gets me something that looks like this. 

![Editor with Forced Title and Subtitle](https://i.ibb.co/3CV53bH/Screen-Shot-2021-11-17-at-5-12-41-PM.png)

There are two caveats in the behavior which I did not expect...

1. When pressing the enter key while the cursor is in the empty title, or empty subtitle, the cursor will not advance to the next line (node).
2. The `block+` in the document content field makes it so you can add infinite (empty) blocks after the required title and subtitle. This is fine, and probably correct, but I am trying to figure out if I can rig it so blocks can only be added if there is content within the previous one, so I am not stuck with a bunch of empty tags. My assumption would be to create another node definition, but I keep running into problems getting the placeholder to display within the child node, and I can't figure out how to prevent the editor from adding nodes when the current content is empty.

If anyone has any suggestions, I am all ears! Hopefully this is a good starting point for you.

**Comment by hanspagel** [comment]
Thanks for sharing, but this is really off topic. If there are more questions related to title/subtitle documents, please open a new question under discussions.

**Comment by rezaffm** [comment]
True, looking forward to your stable release guys

**Comment by felix-berlin** [comment]
> Will more complete image extension (like resizeable, custom upload, Caption, paste image) be part of stable version?

That's exactly what I want too!

**Comment by sereneinserenade** [comment]
Here's the repo https://github.com/sereneinserenade/tiptap-media-resize. You can try it out here https://sereneinserenade.github.io/tiptap-media-resize/ and here's a demo video.

https://user-images.githubusercontent.com/45892659/178123048-0257e732-8cc2-466b-8447-1e2b7cd1b5d9.mov

**Comment by creatorrr** [comment]
Thanks for the awesome work, @philippkuehn ! Quick question: I got a bunch of errors from the typescript compiler when I tried building my tiptap project for `@tiptap/core`. Still trying to figure out if I am doing something wrong but I thought I'd report these anyway.

```sh
(...clipped)

node_modules/@tiptap/core/src/helpers/isList.ts:20:59 - error TS2339: Property 'group' does not exist on type 'NodeConfig<any, any>'.

20   const group = callOrReturn(getExtensionField<NodeConfig['group']>(extension, 'group', context))
                                                             ~~~~~~~

node_modules/@tiptap/core/src/pasteRules/nodePasteRule.ts:31:12 - error TS2339: Property 'deleteRange' does not exist on type 'ChainedCommands'.

31           .deleteRange(range)
              ~~~~~~~~~~~


Found 190 errors in 61 files.

Errors  Files
     1  node_modules/@tiptap/core/src/Editor.ts:103
    28  node_modules/@tiptap/core/src/Extension.ts:70
    18  node_modules/@tiptap/core/src/ExtensionManager.ts:57
    28  node_modules/@tiptap/core/src/Mark.ts:76
    29  node_modules/@tiptap/core/src/Node.ts:76
     2  node_modules/@tiptap/core/src/NodeView.ts:243
     1  node_modules/@tiptap/core/src/commands/blur.ts:14
     1  node_modules/@tiptap/core/src/commands/clearContent.ts:14
     1  node_modules/@tiptap/core/src/commands/clearNodes.ts:16
     2  node_modules/@tiptap/core/src/commands/command.ts:5
     1  node_modules/@tiptap/core/src/commands/createParagraphNear.ts:16
     1  node_modules/@tiptap/core/src/commands/deleteNode.ts:17
     1  node_modules/@tiptap/core/src/commands/deleteRange.ts:14
     1  node_modules/@tiptap/core/src/commands/deleteSelection.ts:16

(...clipped)
```

```sh
npx tsc --version                                                                                                                                                      3s
Version 4.8.2
```

**Comment by bdbch** [comment]
Hey @creatorrr what are your Tiptap package versions? It seems like you have some mismatching of Prosemirror versions going on which results in Typescript errors.

**Comment by bdbch** [comment]
I am going to close this issue for now.

Everything from the original list for 2.0.0 is done by now, but I have found a few weird editor behaviors (thanks to @rfgamaral) that I would like to fix before 2.0.0 including weird joining of nodes when backspace or delete is used that is not in line with expected behaviors from Google Docs, Dropbox Paper and Co. (which are usually the solutions people would expect from a text editor).

We also have some open issues about NodeViews that we should fix before releasing a stable version.

We have a 2.0.0 Milestone for now and will plan out potential open issues for our stable release in there.

**Comment by rfgamaral** [comment]
Hey @bdbch, I want to propose a few additional issues for the v2.0.0 milestone. I am a bit biased on these, yes, but I believe that most of these are just as important for a stable v2. Also note that some of them have been closed by stale bot, but they still exist.

Most of them are related to the suggestion utility, which, IMO, needs a lot of improvement and is currently a bit buggy:

* https://github.com/ueberdosis/tiptap/issues/214
* https://github.com/ueberdosis/tiptap/issues/2159
* https://github.com/ueberdosis/tiptap/issues/2547
* https://github.com/ueberdosis/tiptap/issues/2592
* https://github.com/ueberdosis/tiptap/issues/2680

Then, a few others with lower priority:

* https://github.com/ueberdosis/tiptap/issues/1964
* https://github.com/ueberdosis/tiptap/issues/2570
